"""empty message

Revision ID: 291b9e24dc2d
Revises: cce5af25ad68
Create Date: 2025-05-19 16:51:49.076575

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '291b9e24dc2d'
down_revision = 'cce5af25ad68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.String(length=100), nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('transaction_id')

    # ### end Alembic commands ###
