"""empty message

Revision ID: 322ed8666152
Revises: 33be3f02165a
Create Date: 2025-05-13 14:09:32.794286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '322ed8666152'
down_revision = '33be3f02165a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###
