"""empty message

Revision ID: 33be3f02165a
Revises: c842235ebac1
Create Date: 2025-05-12 17:42:53.734091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33be3f02165a'
down_revision = 'c842235ebac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
