"""empty message

Revision ID: 409435255eb4
Revises: cd6760d850f0
Create Date: 2025-05-19 16:46:46.459074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '409435255eb4'
down_revision = 'cd6760d850f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('redirect_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('redirect_url')

    # ### end Alembic commands ###
