"""empty message

Revision ID: 6ab95aafa36e
Revises: ebfc92b7e8dc
Create Date: 2024-12-23 16:27:53.085413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ab95aafa36e'
down_revision = 'ebfc92b7e8dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_description', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('product_image', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_column('product_image')
        batch_op.drop_column('product_description')

    # ### end Alembic commands ###
