"""empty message

Revision ID: 870d28c80f71
Revises: 6ab95aafa36e
Create Date: 2024-12-23 16:36:07.644074

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '870d28c80f71'
down_revision = '6ab95aafa36e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_column('product_image')
        batch_op.drop_column('product_description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_description', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('product_image', mysql.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
