"""empty message

Revision ID: cd6760d850f0
Revises: 9e8a05360485
Create Date: 2025-05-19 16:21:02.701233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd6760d850f0'
down_revision = '9e8a05360485'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_amount', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('currency')
        batch_op.drop_column('total_amount')

    # ### end Alembic commands ###
