"""empty message

Revision ID: efec22e5bffb
Revises: 60c47a23dd16
Create Date: 2024-09-23 18:09:58.450985

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'efec22e5bffb'
down_revision = '60c47a23dd16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.String(length=40), nullable=False))
        batch_op.drop_constraint('carts_ibfk_1', type_='foreignkey')
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('carts_ibfk_1', 'customers', ['customer_id'], ['id'])
        batch_op.drop_column('product_name')

    # ### end Alembic commands ###
